global Version := "1.0.0"

Plants := [
    {Name: "Carrot",                    Value: 0},
    {Name: "Strawberry",                Value: 0},
    {Name: "Blueberry",                 Value: 0},
    {Name: "Tulip",                     Value: 0},
    {Name: "Tomato",                    Value: 0},
    {Name: "Apple",                     Value: 0},
    {Name: "Bamboo",                    Value: 0},
    {Name: "Corn",                      Value: 0},
    {Name: "Cactus",                    Value: 0},
    {Name: "Pineapple",                 Value: 0},
    {Name: "Mushroom",                  Value: 0},
    {Name: "GreenBean",                 Value: 0},
    {Name: "Banana",                    Value: 0},
    {Name: "Grape",                     Value: 0},
    {Name: "Coconut",                   Value: 0},
    {Name: "Mango",                     Value: 0},
    {Name: "DragonFruit",               Value: 0},
    {Name: "Acorn",                     Value: 0},
    {Name: "Cherry",                    Value: 0},
    {Name: "Sunflower",                 Value: 0},
    {Name: "VenusFlyTrap",              Value: 0},
    {Name: "Pomegranate",               Value: 0},
    {Name: "PoisonApple",               Value: 0},
    {Name: "Venom Spitter",             Value: 0},
    {Name: "MoonBloom",                 Value: 0},
    {Name: "HypnoBloom",                Value: 0},
    {Name: "DragonsBreath",             Value: 0},
]

Gears := [
    {Name: "CommonWateringCan",         Value: 0},
    {Name: "CommonSprinkler",           Value: 0},
    {Name: "Sign",                      Value: 0},
    {Name: "UncommonSprinkler",         Value: 0},
    {Name: "Trowel",                    Value: 0},
    {Name: "RareSprinkler",             Value: 0},
    {Name: "JumpMushroom",              Value: 0},
    {Name: "SpeedMushroom",             Value: 0},
    {Name: "Megaphone",                 Value: 0},
    {Name: "ShrinkMushroom",            Value: 0},
    {Name: "SupersizeMushroom",         Value: 0},
    {Name: "Gnome",                     Value: 0},
    {Name: "Flashbang",                 Value: 0},
    {Name: "BasicPot",                  Value: 0},
    {Name: "InvisibilityMushroom",      Value: 0},
    {Name: "LegendarySprinkler",        Value: 0},
    {Name: "Wheelbarrow",               Value: 0},
    {Name: "PlayerMagnet",              Value: 0},
    {Name: "StrawberrySniper",          Value: 0},
    {Name: "SuperWateringCan",          Value: 0},
    {Name: "SuperSprinkler",            Value: 0},
]

Coordinates := [
    {Name: "Seeds", Value1: 226, Value2: 117},
    {Name: "Garden", Value1: 402, Value2: 117},
    {Name: "Sell", Value1: 580, Value2: 118},
    {Name: "XButton", Value1: 635, Value2: 184},
    {Name: "NextItem", Value1: 401, Value2: 446},
]